// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.AuthProxy.Authentication.for_AuthenticationServiceCollectionExtensions.when_validating_oauth_authorization_parameters;

/// <summary>
/// Specifies that configured authorization parameters cannot replace values generated by the OAuth handler.
/// </summary>
public class and_a_parameter_is_framework_owned : given.canonical_configuration_validation
{
    IServiceProvider _services = null!;
    Exception? _exception;

    void Establish()
    {
        var configuration = ValidOAuthProvider();
        configuration[$"{C.Authentication.SectionKey}:OAuthProviders:0:AuthorizationParameters:STATE"] = "consumer-state";
        _services = BuildServices(configuration);
    }

    void Because() => _exception = ResolveAuthenticationOptions(_services);

    [Fact] void should_fail_configuration_validation() => _exception.ShouldBeOfExactType<OptionsValidationException>();
}
